// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGdEU0wSBKuONiEScqSkl--eQTWQoSB7U',
    appId: '1:383346744968:web:03af9a5a31041da516493d',
    messagingSenderId: '383346744968',
    projectId: 'pookie-store',
    authDomain: 'pookie-store.firebaseapp.com',
    storageBucket: 'pookie-store.firebasestorage.app',
    measurementId: 'G-4ZK8CJBM8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrqWfKyHUk2WUBF9HHavJIfvcTcq8K5y0',
    appId: '1:383346744968:android:a1b5f07ec3cd399c16493d',
    messagingSenderId: '383346744968',
    projectId: 'pookie-store',
    storageBucket: 'pookie-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUB2Rrr6xSHOiLVYhKGXTyNw-EoSt5jgk',
    appId: '1:383346744968:ios:4cdb6d50eddb905a16493d',
    messagingSenderId: '383346744968',
    projectId: 'pookie-store',
    storageBucket: 'pookie-store.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );
}
